# Autostart necessary processes (like notifications daemons, status bars, etc.)                                              

# Utils

exec-once = quickshell
exec-once = dunst
exec-once = vicinae server
exec-once = pypr
exec-once = hypridle
exec-once = hyprpaper
exec-once = systemctl --user start hyprpolkitagent
exec-once = kwalletd6
exec-once = hyprpm reload

# Apps

exec-once = vesktop -minimzed
exec-once = steam -silent %U
