wallpaper {
    monitor = DP-1
    path = ~/Pictures/Wallpapers/main.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = ~/Pictures/Wallpapers/black and purple clouds.jpg
    fit_mode = cover
}
wallpaper {
    monitor =
    path = ~/Pictures/Wallpapers/galaxy.jpg
    fit_mode = cover
}
