[pyprland]
plugins = [
    "shortcuts_menu",
    "system_notifier"
]


[shortcuts_menu.entries."quickstart"]
"1. firefox"  = "firefox"
"2. vesktop"  = "vesktop"
"3. vscode"   = "code"
"4. intellij" = "idea"


[shortcuts_menu.entries."games"]
"a. Steam"  = "steam"
"b. Prism"  = "prismlauncher"
"c. CKAN"	= "ckan"
"========"  = ""
"1. Titanfall 2" = "steam steam://rungameid/1237970"
"2. Balatro"     = "steam steam://rungameid/2379780"
"3. Spirit Lofi" = "steam steam://rungameid/2113850"
"4. Beyond all Reason "	= "/home/anu/games/Beyond-All-Reason-1.2988.0.AppImage"
"5. Final Fantasy 14"	= "steam steam://rungameid/312060"
"6. Elite Dangerous"	= "steam steam://rungameid/359320"
